### ISSUE TITLE
Copy/paste a text label still fails in 3.4.5 

### ISSUE THREAD

**Issue by CuriousMarc** [reds-heig/logisim-evolution#557]
Thanks for quickly fixing most of the text label issue. There is still a small part of the bug that's left in 3.4.5 though:
 If you try to copy and paste a text label, it comes up with an error that says:
"Some clipboard components were not pasted because the project libraries do not support them:
  Label"
Admittedly a minor annoyance, now that the text label is mostly working again.
Marc

**Comment by BFH-ktt1** [comment]
@CuriousMarc , Thanks for the bug report, I'll look into the details

**Comment by zdimension** [comment]
Fixed in fff841, see PR #558

**Comment by CuriousMarc** [comment]
Thanks!

Marc

 

From: "Prof. Dr. Theo Kluter" ***@***.***>
Reply-To: reds-heig/logisim-evolution ***@***.***>
Date: Friday, May 7, 2021 at 12:55 PM
To: reds-heig/logisim-evolution ***@***.***>
Cc: Marc Verdiell ***@***.***>, Mention ***@***.***>
Subject: Re: [reds-heig/logisim-evolution] Copy/paste a text label still fails in 3.4.5 (#557)

 

I close this issue as the latest PR of @zdimension fixes the problem, please reopen in case the problem persists
